name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 21.0.5
      uses: actions/setup-java@v1
      with:
        java-version: '21.0.5'
        java-package: jdk
        architecture: x64

    - name: Build with Maven
      run: mvn -B package --file pom.xml
